name = "BetterMoon"
author = "Mendo85"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c44c89e710e5816b3ad6cc53c8a032313a642484671eca220e9c95177d0681e7"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
