name = "BetterMoon"
author = "Mendo85"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72ca17eb6cdb4f84419bff173051c57894f3ebbf52560e94f34829ed0a42ae99"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
