name = "BetterMoon"
author = "Mendo85"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d8a22753cebd136efc584482a7a3977f490480d7bc53b78ab3300a9e8856d15"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
