#Cobblemon Leaderboards server config
#Sat Aug 15 16:27:46 CEST 2026
config_version=2
hologram_footer_refresh_seconds=30
network_database.enabled=false
network_database.jdbc_url=jdbc\:postgresql\://localhost\:5432/cobblemon_leaderboards
network_database.password=
network_database.refresh_seconds=30
network_database.server_id=server_1
network_database.username=
preview_duration_seconds=90
refresh_interval_minutes=5
